### ISSUE TITLE
Question about documentation or readme

### ISSUE THREAD

**Issue by bakelew** [clavin/electron-native-auth#2]
Hi there, apologies if this is not the best place to be asking for general queries.

I'm interested in using this package in our electron application to improve the SSO authentication. Though, I'm wondering about the usage of this package, what it does, and how it fits together with Electron.

From what I understand, it's used as part of the authentication flow in Slack, and am wondering if there is any readme available, or documentation about this package that we could refer to?

Thanks!

**Comment by clavin** [comment]
Hiya! 👋 This is a great place to ask :) (Sorry about not seeing this until now!)

I wrote up a read-me that explains the purpose, state, and usage of this package. Feel free to reach out if I can help clarify anything in it! If not, feel free to close this issue. 😄

**Comment by bakelew** [comment]
Thank you very much for that, it is greatly appreciated and covers all the questions I had. Thanks again!
