### ISSUE TITLE
cancel method doesn't cancel `AsWebAuthenticationSession` request

### ISSUE THREAD

**Issue by jacksman** [clavin/electron-native-auth#3]
Hi there, 

I tested the library and discovered that the `cancel` method doesn't call the `AsWebAuthenticationSession` one ([doc](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/cancel())).
As a result, the opened authentication window is never discarded. 
Additionally, calling the cancel method doesn't reject the promise returned by `start`, causing the promise to never end.

Is there a reason why it isn't doing this? 🤔

If not, I ended up patching my version using the following code, and it seems to work as expected.
If it sounds good to you, it would be great to have it merged into the library.

```

diff --git a/node_modules/electron-native-auth/src/addon_mac.mm b/node_modules/electron-native-auth/src/addon_mac.mm
index 94b95b7..418d1ae 100644
--- a/node_modules/electron-native-auth/src/addon_mac.mm
+++ b/node_modules/electron-native-auth/src/addon_mac.mm
@@ -312,6 +312,10 @@ Napi::Value AuthRequest::Cancel(const Napi::CallbackInfo& info) {
     THROW_ERR_AND_RETURN_UNDEFINED(
         env, "this auth request has not been started, cannot be canceled");
   }
+  // PATCH - cancel request and reject promise
+  [webAuthSess_.get() cancel];
+  promise_.Reject(Napi::Error::New(env_, "Canceled").Value());
+  // PATCH END
 
   // Make our reference to this object weak again since we're no longer in a
   // request

```

**Comment by clavin** [comment]
Thanks for reporting this oversight! Should be fixed in v0.2.0 😄
